### ISSUE TITLE
[CI] Add code scanning

### ISSUE THREAD

**Issue by LiorBanai** [Analogy-LogViewer/Analogy.LogViewer#522]

**Comment by LiorBanai** [comment]
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000007e7d00000, 162529280, 0) failed; error='The paging file is too small for this operation to complete' (DOS error/errno=1455)
  #
  # There is insufficient memory for the Java Runtime Environment to continue.
  # Native memory allocation (mmap) failed to map 162529280 bytes for Failed to commit area from 0x00000007e7d00000 to 0x00000007f1800000 of length 162529280.
  # An error report file with more information is saved as:
  # D:\a\Analogy.LogViewer\Analogy.LogViewer\hs_err_pid5004.log
  Error: Error running analysis for csharp: Error: The process 'C:\hostedtoolcache\windows\CodeQL\0.0.0-20200826\x64\codeql\codeql.exe' failed with exit code 1
  Error: The process 'C:\hostedtoolcache\windows\CodeQL\0.0.0-20200826\x64\codeql\codeql.exe' failed with exit code 1
  Error: No SARIF files found to upload in "../results".
  Error: No SARIF files found to upload in "../results".
      at Object.upload (D:\a\_actions\github\codeql-action\v1\lib\upload-lib.js:82:19)
      at Object.runAnalyze (D:\a\_actions\github\codeql-action\v1\lib\analyze.js:96:42)
      at async run (D:\a\_actions\github\codeql-action\v1\lib\analyze-action.js:42:17)
