### ISSUE TITLE
App hangs when trying to load file in use

### ISSUE THREAD

**Issue by vocko** [Analogy-LogViewer/Analogy.LogViewer#636]
## Bug description
In the latest versions I'm getting this when trying to read a file that is being used by the IIS. It doesn't show any lines from the log file and just hangs with the progressbarr on the bottom making circles. I did not have this problem with the older versions (up to 4.2.8 at least). Shouldn't it be good enough with read-only access?

Not sure what the path "`D:\a\Analogy.LogViewer`" means as it doesn't exist on my machine.

```
Error parsing file: System.IO.IOException: The process cannot access the file 'logfile.clef' because it is being used by another process.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at System.IO.File.ReadAllText(String path)
   at Analogy.LogViewer.Serilog.IAnalogy.OfflineDataProvider.TryDetectFormat(String fileName)
   at Analogy.LogViewer.Serilog.IAnalogy.OfflineDataProvider.Process(String fileName, CancellationToken token, ILogMessageCreatedHandler messagesHandler)
   at Analogy.FileProcessor.Process(IAnalogyOfflineDataProvider fileDataProvider, String filename, CancellationToken token, Boolean isReload) in D:\a\Analogy.LogViewer\Analogy.LogViewer\Analogy\FileProcessor.cs:line 80
```

Also seeing a few other exceptions that don't affect me though:
```

C:\Program Files\Analogy Log Viewer\Analogy.LogViewer.WhatsApp.dll: Error during data providers: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Method 'RegisterNotificationCallback' in type 'Analogy.LogViewer.WhatsApp.IAnalogy.WhatsAppTextParserFactory' from assembly 'Analogy.LogViewer.WhatsApp, Version=1.3.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at Analogy.Managers.ExternalDataProviders..ctor() in D:\a\Analogy.LogViewer\Analogy.LogViewer\Analogy\Managers\ExternalDataProviders.cs:line 60
System.TypeLoadException: Method 'RegisterNotificationCallback' in type 'Analogy.LogViewer.WhatsApp.IAnalogy.WhatsAppTextParserFactory' from assembly 'Analogy.LogViewer.WhatsApp, Version=1.3.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation. (. C:\Program Files\Analogy Log Viewer\Analogy.LogViewer.WhatsApp.dll)
```
```
C:\Program Files\Analogy Log Viewer\Analogy.LogViewer.VisualStudioActivityLog.dll: Error during data providers: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Method 'RegisterNotificationCallback' in type 'Analogy.LogViewer.VisualStudioActivityLog.IAnalogy.VSActivityLogFactory' from assembly 'Analogy.LogViewer.VisualStudioActivityLog, Version=1.3.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at Analogy.Managers.ExternalDataProviders..ctor() in D:\a\Analogy.LogViewer\Analogy.LogViewer\Analogy\Managers\ExternalDataProviders.cs:line 60
System.TypeLoadException: Method 'RegisterNotificationCallback' in type 'Analogy.LogViewer.VisualStudioActivityLog.IAnalogy.VSActivityLogFactory' from assembly 'Analogy.LogViewer.VisualStudioActivityLog, Version=1.3.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation. (. C:\Program Files\Analogy Log Viewer\Analogy.LogViewer.VisualStudioActivityLog.dll)
```

```
C:\Program Files\Analogy Log Viewer\Analogy.LogViewer.GitHistory.dll: Error during data providers: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Method 'get_ConnectedLargeImage' in type 'Analogy.LogViewer.GitHistory.GitRepositoryLoader' from assembly 'Analogy.LogViewer.GitHistory, Version=1.0.9.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'LogInformation' in type 'Analogy.LogViewer.GitHistory.Managers.LogManager' from assembly 'Analogy.LogViewer.GitHistory, Version=1.0.9.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'set_FactoryId' in type 'Analogy.LogViewer.GitHistory.IAnalogy.GitHistoryDataProviderFactory' from assembly 'Analogy.LogViewer.GitHistory, Version=1.0.9.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'set_FactoryId' in type 'Analogy.LogViewer.GitHistory.IAnalogy.GitHistoryFactory' from assembly 'Analogy.LogViewer.GitHistory, Version=1.0.9.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'get_Id' in type 'Analogy.LogViewer.GitHistory.GitActions.GitFetchAction' from assembly 'Analogy.LogViewer.GitHistory, Version=1.0.9.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at Analogy.Managers.ExternalDataProviders..ctor() in D:\a\Analogy.LogViewer\Analogy.LogViewer\Analogy\Managers\ExternalDataProviders.cs:line 60
System.TypeLoadException: Method 'get_ConnectedLargeImage' in type 'Analogy.LogViewer.GitHistory.GitRepositoryLoader' from assembly 'Analogy.LogViewer.GitHistory, Version=1.0.9.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
System.TypeLoadException: Method 'LogInformation' in type 'Analogy.LogViewer.GitHistory.Managers.LogManager' from assembly 'Analogy.LogViewer.GitHistory, Version=1.0.9.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
System.TypeLoadException: Method 'set_FactoryId' in type 'Analogy.LogViewer.GitHistory.IAnalogy.GitHistoryDataProviderFactory' from assembly 'Analogy.LogViewer.GitHistory, Version=1.0.9.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
System.TypeLoadException: Method 'set_FactoryId' in type 'Analogy.LogViewer.GitHistory.IAnalogy.GitHistoryFactory' from assembly 'Analogy.LogViewer.GitHistory, Version=1.0.9.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
System.TypeLoadException: Method 'get_Id' in type 'Analogy.LogViewer.GitHistory.GitActions.GitFetchAction' from assembly 'Analogy.LogViewer.GitHistory, Version=1.0.9.0, Culture=neutral, PublicKeyToken=null' does not have an implementation. (. C:\Program Files\Analogy Log Viewer\Analogy.LogViewer.GitHistory.dll)
```

## ℹ Computer information

 - OS: Windows 10 Version 2004 64 bit
 - Analogy Version 4.2.11 .NET Core 3.1

## 📝 Reproduction steps

1. Open log file that is being used by another process (ie. written by a running application).
2. Click on the file on the left pane.
3. Nothing appears in the main panel.

**Comment by LiorBanai** [comment]
oops,I have added auto detect file format to Serilog parser but forgot to account for file permissions :)
